### ISSUE TITLE
请问这个会开源吗

### ISSUE THREAD

**Issue by OdinLin** [fuslab/jdp#1]
看了下 整个架构 非常的棒， 但是在哪里能看源码呢， 相关的仓库都是空的，是我的打开方式不对吗

**Comment by realXuJiang** [comment]
master目前没有内容，主要在分支上开发。

**Comment by OdinLin** [comment]
恩恩  了解了哈  看了下  Core Data和Core AI没有看到相关的， 是否还在开发计划中呢

**Comment by realXuJiang** [comment]
设计：https://tech.jikelab.com/labs-docs/zh-cn/docs/advanced/architecture.html

**Comment by OdinLin** [comment]
恩恩   我也是看了这篇文档才有这个疑问的， 我这边也会开发相关的东西 目前有看到开源的  cdap https://github.com/caskdata/cdap 貌似会有点类似。  多谢多谢
