### ISSUE TITLE
更新clickhouse

### ISSUE THREAD

**Issue by cmdares** [fuslab/jdp#2]
首先表示感谢，最近在研究这块和clickhouse，由于近一两周clickhouse会发布大版本，更新很多实用功能，希望jdp可以跟上clickhouse的主板本，也希望在项目中可以成功运用jdp来做运控。
hadoop太费钱、费事、费心。希望可以转型到kafka加clickhouse，jdp正是理想中需要的平台。
感谢您和团队的辛勤付出！

**Comment by realXuJiang** [comment]
* 目前有计划更新到比较新的稳定版本
* clickhouse版本变更比较快，带稳定版测试无重大故障，我们会发布新的JDP版本
